config/routes.rb
Rails.application.routes.draw do
  resources :billing_details
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :shipments
  resources :payments

  ActiveAdmin.routes(self)
  devise_for ActiveAdmin::Devise.config

  devise_for :users, path_names: { sign_up: 'register' },
             controllers: {  omniauth_callbacks:  'users/omniauth_callbacks',
                             sessions:            'sessions',
                             registrations:       'registrations',
                             passwords:           'passwords'
             }

  get 'pages/index'
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'category' => 'products#category'

  get 'dashboard' => 'users#dashboard'
  get 'user_info' => 'users#info'
  post 'account_settings' => 'users#account_settings'
  get 'order_list' => 'users#order_list'
  get 'order_details/:id' => 'users#order_details', as: :order_details
  get 'manage_address' => 'users#manage_address'

  get 'cart' => 'carts#cart'
  get 'cart_items' => 'carts#cart_items'
  get 'checkout' => 'orders#checkout', :as => :checkout
  get 'shipping_info' => 'orders#shipping_info', as: :shipping_info
  get 'billing_info' => 'orders#billing_info', :as => :billing_info
  get 'shipping_method' => 'orders#shipping_method', :as => :shipping_method
  get 'payment_info' => 'orders#payment_info', :as => :payment_info
  get 'review_order' => 'orders#review_order', :as => :review_order
  get 'confirm_order' => 'orders#confirm_order'
  get 'remove_item_from_cart/:id' => 'line_items#remove_item_from_cart'
  post 'save_shipping_address' => 'orders#save_shipping_address', as: :save_shipping_address, via: [:post]
  get 'filter_products' => 'products#filter_products'

  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  ####<$ Model Association $>####
  has_one :customer
  has_many :orders
  has_and_belongs_to_many :roles

  ####<$ Validation $>####
  # validates_presence_of :first_name, :last_name, :email, :encrypted_password
  #validates_presence_of :email, :encrypted_password
  # after_create :add_role_for_user


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        create_from_omniauth_facebook(auth)
      end
    end
  end

  def self.create_from_omniauth_facebook(auth)
    user                          = self.new
    user.first_name               = auth['info']['first_name']
    user.last_name                = auth['info']['last_name']
    user.profile_picture_provider = auth['info']['image']
    user.provider                 = auth['provider']
    user.uid                      = auth['uid']
    user.email                    = auth['info']['email']
    user.password                 = Devise.friendly_token[0,20]

    if auth['extra']['raw_info']['gender'] == 'male' || auth['extra']['raw_info']['gender'] == 'female'
      user.gender                 = auth['extra']['raw_info']['gender']
    end

    user.save(validate: true)
    user
  end

  def role?(role)
    !!self.roles.find_by_name(role.to_s.camelize)
  end

  private

  def add_role_for_user
    RolesUsers.create!(role_id: Role::USER_ROLE[:user], user_id: self.id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in(@user, event: :authentication)
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      redirect_to session.has_key?(:return_url) ? session.delete(:return_url) : root_path
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def info
    @user = current_user
  end

  def account_settings
    @user = current_user

    if @user.update_attributes(user_params)
      redirect_to user_info_path
    end
  end

  def order_list
    @order_list = Order.user_order_list(current_user.id)
  end

  def order_details
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(:order_id => params[:id])
  end

  def dashboard
  end

  def manage_address
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :mobile, :date_of_birth)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer_dashboard_link.html.haml
%ul.pager
  %li.previous.pull-right
    = link_to(root_path) do
      %i.fa.fa-home
      Go to Shop
  %li.next.pull-left
    = link_to(dashboard_path) do
      &larr; Back to My Dashboard

app/views/users/dashboard.html.haml
.container.main-container.headerOffset
  .row
    .breadcrumbDiv.col-lg-12
      %ul.breadcrumb
        %li
          = link_to 'Home', root_path
        %li.active Dashboard
  .row
    .col-lg-9.col-md-9.col-sm-7
      %h1.section-title-inner
        %span
          %i.fa.fa-unlock-alt
          Dashboard
      .row.userInfo
        .col-xs-12.col-sm-12
          %h2.block-title-2
            %span Welcome to your account. Here you can manage all of your personal information and orders.
          %ul.myAccountList.row
            %li.col-lg-2.col-md-2.col-sm-3.col-xs-4.text-center
              .thumbnail.equalheight
                = link_to(order_list_path) do
                  %i.fa.fa-calendar
                  Order history
            %li.col-lg-2.col-md-2.col-sm-3.col-xs-4.text-center
              .thumbnail.equalheight
                = link_to(manage_address_path) do
                  %i.fa.fa-map-marker
                  My addresses
            -#%li.col-lg-2.col-md-2.col-sm-3.col-xs-4.text-center
            -#  .thumbnail.equalheight
            -#    %a{:href => "add-address.html", :title => "Add  address"}
            -#      %i.fa.fa-edit
            -#      Add  address
            %li.col-lg-2.col-md-2.col-sm-3.col-xs-4.text-center
              .thumbnail.equalheight
                = link_to(user_info_path) do
                  %i.fa.fa-cog
                  Personal information
            -#%li.col-lg-2.col-md-2.col-sm-3.col-xs-4.text-center
            -#  .thumbnail.equalheight
            -#    %a{:href => "wishlist.html", :title => "My wishlists"}
            -#      %i.fa.fa-heart
            -#      My wishlists
          .clear.clearfix
    .col-lg-3.col-md-3.col-sm-5
  %div{:style => "clear:both"}
.gap

app/views/users/info.html.haml
.container.main-container.headerOffset
  .row
    .breadcrumbDiv.col-lg-12
      %ul.breadcrumb
        %li
          = link_to 'Home', root_path
        %li
          = link_to 'Dashboard', dashboard_path
        %li.active My information
  .row
    .col-lg-9.col-md-9.col-sm-7
      %h1.section-title-inner
        %span
          %i.glyphicon.glyphicon-user
          My personal information
      .row.userInfo
        .col-lg-12
          %h2.block-title-2 Please be sure to update your personal information if it has changed.
          %p.required
            %sup *
            Required field
        = form_for @user, :url => account_settings_path, :html => {:method => :post} do |f|
          .col-xs-12.col-sm-6
            .form-group.required
              %label{:for => "InputName"}
                First Name
                %sup *
              = f.text_field :first_name, class: 'form-control', :placeholder => 'First Name', :size => '50'
            .form-group.required
              %label{:for => "InputLastName"}
                Last Name
                %sup *
              = f.text_field :last_name, class: 'form-control', :placeholder => 'Last Name', :size => '50'
            .form-group
              %label{:for => "InputEmail"} Email
              = f.text_field :email, class: 'form-control', :placeholder => 'Email', :size => '50'
          .col-xs-12.col-sm-6
            .form-group.required
              %label{:for => "InputMobileNumber"}
                Mobile Number
                %sup *
              = f.text_field :mobile, class: 'form-control', :placeholder => 'Mobile', :size => '50'
            .form-group
              %label{:for => "InputDateOfBirth"} Date of Birth
              = f.text_field :date_of_birth, class: 'form-control', :placeholder => 'YYYY-MM-DD', :size => '50', :id=> 'date_of_birth'
          .col-lg-12
            %div
              %div
                = f.submit 'Submit', class:'btn btn-primary', :value => 'Submit'
        .col-lg-12.clearfix
          = render :partial => 'footer_dashboard_link'
    .col-lg-3.col-md-3.col-sm-5
  %div{:style => 'clear:both'}
.gap

:javascript
  $(function(){
    $('#date_of_birth').datepicker({
        format: 'yyyy-mm-dd'
    });
  });

app/views/users/order_details.html.haml
.container.main-container.headerOffset
  .row
    .breadcrumbDiv.col-lg-12
      %ul.breadcrumb
        %li
          = link_to 'Home', root_path
        %li
          = link_to 'Dashboard', dashboard_path
        %li.active Order Detail
  .row
    .col-lg-9.col-md-9.col-sm-7
      %h1.section-title-inner
        %span
          %i.fa.fa-list-alt
          Order Details
      .row.userInfo
        .col-lg-12
          %h2.block-title-2 Product Details
        .col-xs-12.col-sm-12
          %table.footable
            %thead
              %tr
                %th{"data-class" => "expand", "data-sort-initial" => "true"}
                  %span{:title => "table sorted by this column on load"} Product
                %th{"data-class" => "expand", "data-sort-initial" => "true"}
                  %span{:title => "table sorted by this column on load"} Product name
                %th{"data-hide" => "phone,tablet", "data-sort-ignore" => "true"} Quantity
                %th{"data-hide" => "phone,tablet"}
                  %strong Product Price
            %tbody
              - if @order_details.present?
                - @order_details.each do |order_detail|
                  %tr
                    %td{:style => 'text-align:center; width:10%'}
                      = image_tag order_detail.product.product_photos.first.image_url(:thumb_small), :width => 60, :height => 80
                    %td
                      = link_to order_detail.product.name, product_path(order_detail.product.id)
                    %td
                      = order_detail.quantity if order_detail.quantity.present?
                    %td
                      = order_detail.product_price if order_detail.product_price.present?


        .row.userInfo
        .col-lg-12
          %h1.block-title-2 Payment Info
        .col-xs-12.col-sm-12
          %table.footable
            %tbody
              - if @order.present?

                %tr
                  %td{:style => 'width: 20%'}
                    %strong
                      Payment Type
                  %td
                    = @order.payment.payment_type if @order.payment.payment_type.present?
                %tr
                  %td
                    %strong
                      Status
                  %td
                    = @order.payment.status if @order.payment.status.present?

                %tr
                  %td
                    %strong
                      Transaction Number
                  %td
                    = @order.payment.transaction_number if @order.payment.transaction_number.present?

                %tr
                  - if @order.payment.payment_type == Payment::PAYMENT_TYPE[:bikash]
                    %td
                      %strong
                        Transaction Mobile Number
                    %td
                      = @order.payment.transaction_mobile_number if @order.payment.transaction_mobile_number.present?



        .row.userInfo
        .col-lg-12
          %h1.block-title-2 Shipment Details
        .col-xs-12.col-sm-12
          %table.footable
            %tbody
              - if @order.present?
                %tr
                  %td{:style => 'width: 20%'}
                    %strong
                      Status
                  %td
                    = @order.shipment.status if @order.shipment.status.present?
                %tr
                  %td
                    %strong
                      Shipping Date
                  %td
                    = @order.shipment.shipping_date if @order.shipment.shipping_date.present?

                %tr
                  %td
                    %strong
                      First Name
                  %td
                    = @order.shipment.first_name if @order.shipment.first_name.present?
                %tr
                  %td
                    %strong
                      Last Name
                  %td
                    = @order.shipment.last_name if @order.shipment.last_name.present?

                %tr
                  %td
                    %strong
                      Email
                  %td
                    = @order.shipment.email if @order.shipment.email.present?
                %tr
                  %td
                    %strong
                      Company
                  %td
                    = @order.shipment.company if @order.shipment.company.present?

                %tr
                  %td
                    %strong
                      Address
                  %td
                    = @order.shipment.address if @order.shipment.address.present?
                %tr
                  %td
                    %strong
                      City
                  %td
                    = @order.shipment.city if @order.shipment.city.present?

                %tr
                  %td
                    %strong
                      State
                  %td
                    = @order.shipment.state if @order.shipment.state.present?
                %tr
                  %td
                    %strong
                      Zip Code
                  %td
                    = @order.shipment.zip_code if @order.shipment.zip_code.present?

                %tr
                  %td
                    %strong
                      Country
                  %td
                    = @order.shipment.country if @order.shipment.country.present?
                %tr
                  %td
                    %strong
                      Mobile Phone
                  %td
                    = @order.shipment.mobile_phone if @order.shipment.mobile_phone.present?
                %tr
                  %td
                    %strong
                      Additional Information
                  %td
                    = @order.shipment.additional_information if @order.shipment.additional_information.present?



        .row.userInfo
        .col-lg-12
          %h1.block-title-2 Billing Details
        .col-xs-12.col-sm-12
          %table.footable
            %tbody
              - if @order.present?

                %tr
                  %td{:style => 'width: 20%'}
                    %strong
                      First Name
                  %td
                    = @order.billing_detail.first_name if @order.billing_detail.first_name.present?
                %tr
                  %td
                    %strong
                      Last Name
                  %td
                    = @order.billing_detail.last_name if @order.billing_detail.last_name.present?

                %tr
                  %td
                    %strong
                      Email
                  %td
                    = @order.billing_detail.email if @order.billing_detail.email.present?
                %tr
                  %td
                    %strong
                      Company
                  %td
                    = @order.billing_detail.company if @order.billing_detail.company.present?

                %tr
                  %td
                    %strong
                      Address
                  %td
                    = @order.billing_detail.address if @order.billing_detail.address.present?
                %tr
                  %td
                    %strong
                      City
                  %td
                    = @order.billing_detail.city if @order.billing_detail.city.present?

                %tr
                  %td
                    %strong
                      State
                  %td
                    = @order.billing_detail.state if @order.billing_detail.state.present?
                %tr
                  %td
                    %strong
                      Zip Code
                  %td
                    = @order.billing_detail.zip_code if @order.billing_detail.zip_code.present?

                %tr
                  %td
                    %strong
                      Country
                  %td
                    = @order.billing_detail.country if @order.billing_detail.country.present?
                %tr
                  %td
                    %strong
                      Mobile Phone
                  %td
                    = @order.billing_detail.mobile_phone if @order.billing_detail.mobile_phone.present?
                %tr
                  %td
                    %strong
                      Additional Information
                  %td
                    = @order.billing_detail.additional_information if @order.billing_detail.additional_information.present?



        .col-lg-12.clearfix
          = render :partial => 'footer_dashboard_link'
    .col-lg-3.col-md-3.col-sm-5
  %div{:style => 'clear:both'}
.gap

app/views/users/order_list.html.haml
.container.main-container.headerOffset
  .row
    .breadcrumbDiv.col-lg-12
      %ul.breadcrumb
        %li
          = link_to 'Home', root_path
        %li
          = link_to 'Dashboard', dashboard_path
        %li.active Order List
  .row
    .col-lg-9.col-md-9.col-sm-7
      %h1.section-title-inner
        %span
          %i.fa.fa-list-alt
          Order List
      .row.userInfo
        .col-lg-12
          %h2.block-title-2 Your Order List
        .col-xs-12.col-sm-12
          %table.footable
            %thead
              %tr
                %th{"data-class" => "expand", "data-sort-initial" => "true"}
                  %span{:title => "table sorted by this column on load"} Order ID
                %th{"data-hide" => "phone,tablet", "data-sort-ignore" => "true"} No. of items
                -#%th{"data-hide" => "phone,tablet", "data-sort-ignore" => "true"} Invoice
                %th{"data-hide" => "phone,tablet"}
                  %strong Payment Method
                %th{"data-hide" => "default"} Price
                %th{"data-hide" => "default", "data-type" => "numeric"} Date
                %th{"data-hide" => "phone", "data-type" => "numeric"} Status
            %tbody
              - if @order_list.present?
                - @order_list.each do |order|
                  %tr
                    %td
                      = link_to order.id, order_details_path(order.id)
                    %td
                      = order.order_details.count
                      %small item(s)
                    -#%td
                      %a{:target => "_blank"} -
                    %td
                      = order.payment.payment_type if order.payment.present?
                    %td
                      = order.order_total
                    %td{"data-value" => "78025368997"}
                      = order.order_date.strftime("%d-%m-%Y")
                    %td{"data-value" => "3"}
                      - if order.order_status == Order::STATUS[:new]
                        %span.label.label-default
                          = Order::STATUS[:pending]
                      - elsif order.order_status == Order::STATUS[:shipped]
                        %span.label.label-primary
                          = order.order_status if order.order_status.present?
                      - elsif order.order_status == Order::STATUS[:canceled]
                        %span.label.label-danger
                          = order.order_status if order.order_status.present?
                      - elsif order.order_status == Order::STATUS[:confirmed]
                        %span.label.label-success
                          = order.order_status if order.order_status.present?


        .col-lg-12.clearfix
          = render :partial => 'footer_dashboard_link'
    .col-lg-3.col-md-3.col-sm-5
  %div{:style => 'clear:both'}
.gap