config/routes.rb
Rails.application.routes.draw do
  resources :billing_details
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :shipments
  resources :payments

  ActiveAdmin.routes(self)
  devise_for ActiveAdmin::Devise.config

  devise_for :users, path_names: { sign_up: 'register' },
             controllers: {  omniauth_callbacks:  'users/omniauth_callbacks',
                             sessions:            'sessions',
                             registrations:       'registrations',
                             passwords:           'passwords'
             }

  get 'pages/index'
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'category' => 'products#category'

  get 'dashboard' => 'users#dashboard'
  get 'user_info' => 'users#info'
  post 'account_settings' => 'users#account_settings'
  get 'order_list' => 'users#order_list'
  get 'order_details/:id' => 'users#order_details', as: :order_details
  get 'manage_address' => 'users#manage_address'

  get 'cart' => 'carts#cart'
  get 'cart_items' => 'carts#cart_items'
  get 'checkout' => 'orders#checkout', :as => :checkout
  get 'shipping_info' => 'orders#shipping_info', as: :shipping_info
  get 'billing_info' => 'orders#billing_info', :as => :billing_info
  get 'shipping_method' => 'orders#shipping_method', :as => :shipping_method
  get 'payment_info' => 'orders#payment_info', :as => :payment_info
  get 'review_order' => 'orders#review_order', :as => :review_order
  get 'confirm_order' => 'orders#confirm_order'
  get 'remove_item_from_cart/:id' => 'line_items#remove_item_from_cart'
  post 'save_shipping_address' => 'orders#save_shipping_address', as: :save_shipping_address, via: [:post]
  get 'filter_products' => 'products#filter_products'

  root 'pages#home'

end

app/models/order.rb
class Order < ActiveRecord::Base

  ####<$ Model Association $>####
  belongs_to :cart
  has_one :shipment
  has_one :billing_detail
  has_one :payment
  has_many :order_details
  belongs_to :user

  ####<$ Validation $>####
  validates_presence_of :cart_id, :order_date, :order_total

  STATUS = {
      :new => 'New',
      :pending => 'Pending',
      :shipped => 'Shipped',
      :canceled => 'Canceled',
      :confirmed => 'Confirmed'
  }

  ####<$ Scope List $>####
  scope :user_order_list, ->(user_id) { where('user_id =?', user_id)}

  def self.find_with_product(product)
    return [] unless product
    joins(:order_details).
        where(["order_details.product_id = ?", product.id]).
        order("orders.order_date DESC")
  end

  def order_total
    self.order_details.to_a.sum { |item| item.order_total_price }
  end

  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_filter :check_cart_items
  before_filter :skip_checkout, :only => :checkout

  def checkout
    session[:return_url] = shipping_info_path
  end

  def shipping_info
    shipment = Shipment.find_by_cart_id(session[:cart_id])
    @shipment = shipment.present? ? shipment : Shipment.new
  end

  def billing_info
    billing_detail = BillingDetail.find_by_cart_id(session[:cart_id])
    @billing_detail = billing_detail.present? ? billing_detail : BillingDetail.new
  end

  def shipping_method
  end

  def payment_info
    payment  = Payment.find_by_cart_id(session[:cart_id])
    @payment = payment.present? ? payment : Payment.new
  end

  def review_order
    @cart_items = LineItem.where(:cart_id => session[:cart_id])
  end

  def confirm_order
    order = Order.new
    cart  = Cart.find(session[:cart_id])
    cart_total = cart.cart_total.present? ? cart.cart_total : 0
    shipping_cost = cart.shipping_cost.present? ? cart.shipping_cost : 0

    order.user_id = current_user.id if current_user.present?
    order.cart_id = cart.id
    order.order_status = Order::STATUS[:new]
    order.order_date   = Date.today.strftime("%Y-%m-%d")
    order.shipping_cost = shipping_cost
    order.order_total   = cart_total + shipping_cost

    if order.save
      save_order_details(cart, order)
      update_shipment(cart, order)
      update_billing_details(cart, order)
      update_payments(cart, order)
      remove_order_session
    end

  end

  def save_order_details(cart, order)
    line_items = LineItem.where(:cart_id => cart.id)

    line_items.each do |item|
      order_detail = OrderDetail.new

      order_detail.order_id = order.id
      order_detail.product_id = item.product_id
      order_detail.quantity = item.quantity
      order_detail.product_price = item.product_price
      order_detail.save
    end
  end

  def update_shipment(cart, order)
    shipment = Shipment.find_by_cart_id(cart.id)
    shipment.order_id = order.id
    shipment.save
  end

  def update_billing_details(cart, order)
    billing_detail = BillingDetail.find_by_cart_id(cart.id)
    billing_detail.order_id = order.id
    billing_detail.save
  end

  def update_payments(cart, order)
    payment = Payment.find_by_cart_id(cart.id)
    payment.order_id = order.id
    payment.save
  end

  def remove_order_session
    session[:cart_id] = nil

    if session[:cart_id].nil? && current_user.present?
      redirect_to dashboard_path
    elsif session[:cart_id].nil?
      redirect_to root_path
    end
  end

  def check_cart_items
    if session[:cart_id].nil?
      redirect_to root_path
    end
  end

  def skip_checkout
    if current_user.present?
      redirect_to shipping_info_path
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def order_step_class(step)
    classes = {
        '2' => '',
        '3' => '',
        '4' => '',
        '5' => '',
        '6' => ''
    }

    classes['2'] = (step == 'two') ? 'active' : ''
    classes['3'] = (step == 'three') ? 'active' : ''
    classes['4'] = (step == 'four') ? 'active' : ''
    classes['5'] = (step == 'five') ? 'active' : ''
    classes['6'] = (step == 'six') ? 'active' : ''

    classes
  end
end

app/views/orders/_check_header.html.haml
.row
  .breadcrumbDiv.col-lg-12
    %ul.breadcrumb
      %li
        = link_to 'Home', root_path
      %li
        = link_to 'Cart', ''
      %li.active Checkout
/ /.row
.row
  .col-lg-9.col-md-9.col-sm-7
    %h1.section-title-inner
      %span
        %i.glyphicon.glyphicon-shopping-cart
        Checkout
  .col-lg-3.col-md-3.col-sm-5.rightSidebar
    %h4.caps
      %a{:href => '/'}
        %i.fa.fa-chevron-left
        Back to shopping

app/views/orders/_check_nav.html.haml
-#- two_class = ( && step == 'two') ? 'active' : ''
-#- three_class = (defined?(step) && step == 'three') ? 'active' : ''

- begin step rescue step = '' end
- orderStepClass = order_step_class(step)

.w100.clearfix
  %ul.orderStep
    %li{class: orderStepClass['2']}
      %a{:href => shipping_info_path}
        %i.fa.fa-map-marker
        %span address
    %li{class: orderStepClass['3']}
      %a{:href => billing_info_path}
        %i.fa.fa.fa-envelope
        %span Billing
    %li{class: orderStepClass['4']}
      %a{:href => shipping_method_path}
        %i.fa.fa-truck
        %span Shipping
    %li{class: orderStepClass['5']}
      %a{:href => payment_info_url}
        %i.fa.fa-money
        %span Payment
    %li{class: orderStepClass['6']}
      %a{:href => review_order_path}
        %i.fa.fa-check-square
        %span Order

app/views/orders/_check_sidebar.html.haml
.w100.cartMiniTable
  %table#cart-summary.std.table
    %tbody
      %tr
        %td Total products
        %td.price
          {{ grandTotal() }} tk
      %tr{:style => ""}
        %td Shipping
        %td.price
          %span.success Free shipping!
      -#%tr.cart-total-price
      -#  %td Total (tax excl.)
      -#  %td.price $216.51
      -#%tr
      -#  %td Total tax
      -#  %td#total-tax.price $0.00
      %tr
        %td Total
        %td#total-price.site-color
          {{ grandTotal() }} tk
    %tbody
      / /cartMiniTable

app/views/orders/billing_info.html.haml
/ /.Fixed navbar
.container.main-container.headerOffset
  = render partial: 'check_header'
  .row
    .col-lg-9.col-md-9.col-sm-12
      .row.userInfo
        .col-xs-12.col-sm-12
          = render partial: 'check_nav', locals: {step: 'three'}
          .w100.clearfix
            .row.userInfo
              .col-lg-12
                %h2.block-title-2 To add a billing address, please fill out the form below.
              = form_for @billing_detail do |f|
                .col-xs-12.col-sm-6
                  .form-group.required
                    %label{:for => "InputName"}
                      First Name
                      %sup *
                    = f.text_field :first_name, {:class => 'form-control' ,:placeholder => 'First Name', :required => ''}
                  .form-group.required
                    %label{:for => "InputLastName"}
                      Last Name
                      %sup *
                    = f.text_field :last_name, {:class => 'form-control' ,:placeholder => 'Last Name', :required => ''}
                  .form-group
                    %label{:for => "InputEmail"} Email
                    = f.email_field :email, {:class => 'form-control' ,:placeholder => 'Email', :required => ''}
                  .form-group
                    %label{:for => "InputCompany"} Company
                    = f.text_field :company, {:class => 'form-control' ,:placeholder => 'Company'}
                  .form-group.required
                    %label{:for => "InputAddress"}
                      Address
                      %sup *
                    = f.text_area :address, {:class => 'form-control' ,:placeholder => 'Address', :required => ''}
                  .form-group
                    %label{:for => "InputAddress2"} Address (Line 2)
                    = f.text_field :city, {:class => 'form-control' ,:placeholder => 'City', :required => ''}
                  .form-group.required
                    %label{:for => "InputCity"}
                      City
                      %sup *
                    = f.text_field :city, {:class => 'form-control' ,:placeholder => 'City', :required => ''}
                  .form-group.required
                    %label{:for => "InputState"}
                      State
                      %sup *
                    = f.text_field :state, {:class => 'form-control' ,:placeholder => 'State', :required => ''}
                .col-xs-12.col-sm-6
                  .form-group.required
                    %label{:for => "InputZip"}
                      Zip / Postal Code
                      %sup *
                    = f.text_field :zip_code, {:class => 'form-control' ,:placeholder => 'Zip/ Postal Code', :required => ''}
                  .form-group
                    %label{:for => "InputAdditionalInformation"} Additional information
                    = f.text_area :additional_information, {:class => 'form-control' ,:placeholder => 'Additional Information'}
                  .form-group.required
                    %label{:for => "InputMobile"}
                      Mobile phone
                      %sup *
                    = f.text_field :mobile_phone, {:class => 'form-control' ,:placeholder => 'Mobile Phone', :required => ''}
                  .form-group
                    .pull-left
                      = f.submit 'Submit', class:'btn btn-primary', :value => 'Save'

          .cartFooter.w100
            .box-footer
              .pull-left
                %a.btn.btn-default{:href => '/shipping_info'}
                  %i.fa.fa-arrow-left
                  \&nbsp; Shipping address
              .pull-right
                %a.btn.btn-primary.btn-small{:href => '/shipping_method'}
                  Shipping method &nbsp;
                  %i.fa.fa-arrow-circle-right

    .col-lg-3.col-md-3.col-sm-12.rightSidebar
      = render partial: 'check_sidebar'
    / /rightSidebar
  / /row
  %div{:style => "clear:both"}
/ /main-container
.gap

app/views/orders/checkout.html.haml
.container.main-container.headerOffset
  .row
    .breadcrumbDiv.col-lg-12
      %ul.breadcrumb
        %li
          = link_to 'Home', root_path
        %li.active Authentication
  .row
    .col-lg-12.col-md-12.col-sm-12
      %h1.section-title-inner
        %span
          %i.fa.fa-lock
          Authentication
      .row.userInfo
        .col-xs-12.col-sm-4
          %h2.block-title-2 Sign up or Sign in before continue
          %p You need to sign up before continue.
          %a{'data-dismiss' => 'modal', 'data-toggle' => 'modal', :href => '#ModalSignup'}
            %button.btn.btn-primary{:type => 'button'}
              %i.fa.fa-user
              Sign Up
          %p
          %p If you already have account sign in below.
          %a{'data-dismiss' => 'modal', 'data-toggle' => 'modal', :href => '#ModalLogin'}
            %button.btn.btn-primary{:type => 'button'}
              %i.fa.fa-sign-in
              Sign in
        -#%h2.block-title-2
        -#  %span Already registered?
        -#%a{'data-dismiss' => 'modal', 'data-toggle' => 'modal', :href => '#ModalLogin'}
        -#  %button.btn.btn-primary{:type => 'button'}
        -#    %i.fa.fa-sign-in
        -#    Sign in
        -#.col-xs-12.col-sm-4
        -#  %h2.block-title-2
        -#    %span Already registered?
        -#  %a{'data-dismiss' => 'modal', 'data-toggle' => 'modal', :href => '#ModalLogin'}
        -#    %button.btn.btn-primary{:type => 'button'}
        -#      %i.fa.fa-sign-in
        -#      Sign InSign in
        .col-xs-12.col-sm-4
          %h2.block-title-2
            %span Checkout as Guest
          %p Don't have an account and you don't want to register? Checkout as a guest instead!
          %a.btn.btn-primary{:href => 'checkout-1.html'}
            %i.fa.fa-sign-in
            Checkout as Guest
  %div{:style => 'clear:both'}
.gap

app/views/orders/checkout_step_one.html.haml
.container.main-container.headerOffset
  .row
    .breadcrumbDiv.col-lg-12
      %ul.breadcrumb
        %li
          = link_to 'Home', root_path
        %li.active Authentication
  .row
    .col-lg-12.col-md-12.col-sm-12
      %h1.section-title-inner
        %span
          %i.fa.fa-lock
          Authentication
      .row.userInfo
        .col-xs-12.col-sm-4
          %h2.block-title-2 Sign up or Sign in before continue
          %p You need to sign up before continue.
          %a{'data-dismiss' => 'modal', 'data-toggle' => 'modal', :href => '#ModalSignup'}
            %button.btn.btn-primary{:type => 'button'}
              %i.fa.fa-user
              Sign Up
          %p
          %p If you already have account sign in below.
          %a{'data-dismiss' => 'modal', 'data-toggle' => 'modal', :href => '#ModalLogin'}
            %button.btn.btn-primary{:type => 'button'}
              %i.fa.fa-sign-in
              Sign in
          -#%h2.block-title-2
          -#  %span Already registered?
          -#%a{'data-dismiss' => 'modal', 'data-toggle' => 'modal', :href => '#ModalLogin'}
          -#  %button.btn.btn-primary{:type => 'button'}
          -#    %i.fa.fa-sign-in
          -#    Sign in
        -#.col-xs-12.col-sm-4
        -#  %h2.block-title-2
        -#    %span Already registered?
        -#  %a{'data-dismiss' => 'modal', 'data-toggle' => 'modal', :href => '#ModalLogin'}
        -#    %button.btn.btn-primary{:type => 'button'}
        -#      %i.fa.fa-sign-in
        -#      Sign InSign in
        .col-xs-12.col-sm-4
          %h2.block-title-2
            %span Checkout as Guest
          %p Don't have an account and you don't want to register? Checkout as a guest instead!
          %a.btn.btn-primary{:href => 'checkout-1.html'}
            %i.fa.fa-sign-in
            Checkout as Guest
  %div{:style => 'clear:both'}
.gap

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Cart</th>
      <th>Order status</th>
      <th>Order date</th>
      <th>Order total</th>
      <th>Shipping address</th>
      <th>Message by customer</th>
      <th>Comment by admin</th>
      <th>Shipping cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user_id %></td>
        <td><%= order.cart_id %></td>
        <td><%= order.order_status %></td>
        <td><%= order.order_date %></td>
        <td><%= order.order_total %></td>
        <td><%= order.shipping_address %></td>
        <td><%= order.message_by_customer %></td>
        <td><%= order.comment_by_admin %></td>
        <td><%= order.shipping_cost %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/review_order.html.haml
.container.main-container.headerOffset
  = render partial: 'check_header'
  .row
    .col-lg-9.col-md-9.col-sm-12
      .row.userInfo
        .col-xs-12.col-sm-12
          = render partial: 'check_nav', locals: {step: 'six'}
          .w100.clearfix
            .row.userInfo
              .col-lg-12
                %h2.block-title-2 Review Order
              .col-xs-12.col-sm-12
                -#= render :partial => 'cart_items'
                .cartContent.w100.checkoutReview
                  %table.cartTable.table-responsive{:style => "width:100%"}
                    %tbody
                      %tr.CartProduct.cartTableHeader
                        %th{:style => "width:15%"} Product
                        %th.checkoutReviewTdDetails Details
                        %th{:style => "width:10%"} Unit Price
                        %th.hidden-xs{:style => "width:5%"} QNT
                        %th.hidden-xs{:style => "width:10%"} Discount
                        %th{:style => "width:15%"} Total
                      - if @cart_items.present?
                        - @cart_items.each do |cart|
                          %tr.CartProduct
                            %td.CartProductThumb
                              %div
                                = link_to product_path(cart.product.id) do
                                  = image_tag cart.product.product_photos.first.image_url(:thumb_medium)
                            %td
                              .CartDescription
                                %h4
                                  = link_to cart.product.name, product_path(cart.product.id)
                            -#%span.size 12 x 1.5 L
                            %td.delete
                              .price
                                = to_bdt(cart.product.price) if cart.product.price.present?
                            %td.hidden-xs
                              = cart.quantity
                            %td.hidden-xs 0
                            %td.price
                              = (cart.product.price * cart.quantity)
                / cartContent
                .w100.costDetails
                  #order-detail-content.table-block
                    %table#cart-summary.std.table
                      %tr
                        %td Total products
                        %td.price
                          {{ grandTotal() }} tk
                      %tr{:style => ''}
                        %td Shipping
                        %td.price
                          %span.success Free shipping!
                      -#%tr.cart-total-price
                      -#  %td Total (tax excl.)
                      -#  %td.price $216.51
                      -#%tr
                      -#  %td Total tax
                      -#  %td#total-tax.price 0.00
                      %tr
                        %td Total
                        %td#total-price.price
                          {{ grandTotal() }} tk
                      %tbody

          .cartFooter.w100
            .box-footer
              .pull-left
                %a.btn.btn-default{:href => '/payment_info'}
                  %i.fa.fa-arrow-left
                  \&nbsp; Payment method
              .pull-right
                %a.btn.btn-primary.btn-small{:href => '/confirm_order'}
                  Confirm Order &nbsp;
                  %i.fa.fa-check

    .col-lg-3.col-md-3.col-sm-12.rightSidebar
      = render partial: 'check_sidebar'
    / /rightSidebar
  / /row
  %div{:style => "clear:both"}
/ /wrapper
.gap

app/views/orders/shipping_info.html.haml
/ /.Fixed navbar
.container.main-container.headerOffset
  = render partial: 'check_header'
  .row
    .col-lg-9.col-md-9
      .col-sm-12
        .row.userInfo
          .col-xs-12.col-sm-12
            = render partial: 'check_nav', locals: {step: 'two'}
          .w100.clearfix
            .row.userInfo
              .col-lg-12
                %h2.block-title-2 To add a new address, please fill out the form below.
              = form_for @shipment do |f|
                -#= f.hidden_field :country, :value => 'Bangladesh'
                -#= f.hidden_field :cart_id, :value => session[:cart_id]
                .col-xs-12.col-sm-6
                  .form-group.required
                    %label{:for => "InputName"}
                      First Name
                      %sup *
                    = f.text_field :first_name, {:class => 'form-control' ,:placeholder => 'First Name', :required => ''}
                  .form-group.required
                    %label{:for => "InputLastName"}
                      Last Name
                      %sup *
                    = f.text_field :last_name, {:class => 'form-control' ,:placeholder => 'Last Name', :required => ''}
                  .form-group
                    %label{:for => "InputEmail"} Email
                    = f.email_field :email, {:class => 'form-control' ,:placeholder => 'Email', :required => ''}
                  .form-group
                    %label{:for => "InputCompany"} Company
                    = f.text_field :company, {:class => 'form-control' ,:placeholder => 'Company'}
                  .form-group.required
                    %label{:for => "InputAddress"}
                      Address
                      %sup *
                    = f.text_area :address, {:class => 'form-control' ,:placeholder => 'Address', :required => ''}
                  .form-group.required
                    %label{:for => "InputCity"}
                      City
                      %sup *
                    = f.text_field :city, {:class => 'form-control' ,:placeholder => 'City', :required => ''}
                  .form-group.required
                    %label{:for => "InputState"}
                      State
                      %sup *
                    = f.text_field :state, {:class => 'form-control' ,:placeholder => 'State', :required => ''}
                .col-xs-12.col-sm-6
                  .form-group.required
                    %label{:for => "InputZip"}
                      Zip / Postal Code
                      %sup *
                    = f.text_field :zip_code, {:class => 'form-control' ,:placeholder => 'Zip/ Postal Code', :required => ''}
                  .form-group
                    %label{:for => "InputAdditionalInformation"} Additional information
                    = f.text_area :additional_information, {:class => 'form-control' ,:placeholder => 'Additional Information'}
                  .form-group.required
                    %label{:for => "InputMobile"}
                      Mobile phone
                      %sup *
                    = f.text_field :mobile_phone, {:class => 'form-control' ,:placeholder => 'Mobile Phone', :required => ''}
                    .form-group
                      .pull-left
                        = f.submit 'Submit', class:'btn btn-primary', :value => 'Save'

          .cartFooter.w100
            .box-footer
              .pull-left
                %a.btn.btn-default{:href => '/'}
                  %i.fa.fa-arrow-left
                  \&nbsp; Back to Shop
              .pull-right
                %a.btn.btn-primary.btn-small{:href => '/billing_info'}
                  Billing address &nbsp;
                  %i.fa.fa-arrow-circle-right

    .col-lg-3.col-md-3.col-sm-12.rightSidebar
      = render partial: 'check_sidebar'
    / /rightSidebar
  / /row
  %div{:style => "clear:both"}
/ /.main-container
.gap

app/views/orders/shipping_method.html.haml
/ /.Fixed navbar
.container.main-container.headerOffset
  = render partial: 'check_header'
  .row
    .col-lg-9.col-md-9.col-sm-12
      .row.userInfo
        .col-xs-12.col-sm-12
          = render partial: 'check_nav', locals: {step: 'four'}
          .w100.clearfix
            .row.userInfo
              .col-lg-12
                %h2.block-title-2 Choose your delivery method

                .form-group.col-lg-12.col-sm-12.col-md-12.-col-xs-12
                  %table.table-bordered.table{:style => "width:100%"}
                    %tbody
                      %tr
                        %td Carrier
                        %td Method
                        %td Information
                        %td Price!
                      %tr
                        %td
                          %label.radio
                            %input#optionsRadios2{:checked => "", :name => "optionsRadios", :type => "radio", :value => "option2"}
                              %i.fa.fa-truck.fa-2x
                        %td By Road
                        %td Delivery next day!
                        %td Free!
                / /row
                .cartFooter.w100
                  .box-footer
                    .pull-left
                      %a.btn.btn-default{:href => '/billing_info'}
                        %i.fa.fa-arrow-left
                        \&nbsp; Shipping address
                    .pull-right
                      %a.btn.btn-primary.btn-small{:href => '/payment_info'}
                        Payment Method &nbsp;
                        %i.fa.fa-arrow-circle-right

    .col-lg-3.col-md-3.col-sm-12.rightSidebar
      = render partial: 'check_sidebar'
    / /rightSidebar
  / /row
  %div{:style => "clear:both"}
/ /main-container
.gap

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @order.cart_id %>
</p>

<p>
  <strong>Order status:</strong>
  <%= @order.order_status %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @order.order_date %>
</p>

<p>
  <strong>Order total:</strong>
  <%= @order.order_total %>
</p>

<p>
  <strong>Shipping address:</strong>
  <%= @order.shipping_address %>
</p>

<p>
  <strong>Message by customer:</strong>
  <%= @order.message_by_customer %>
</p>

<p>
  <strong>Comment by admin:</strong>
  <%= @order.comment_by_admin %>
</p>

<p>
  <strong>Shipping cost:</strong>
  <%= @order.shipping_cost %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>