config/routes.rb
Rails.application.routes.draw do
  resources :billing_details
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :shipments
  resources :payments

  ActiveAdmin.routes(self)
  devise_for ActiveAdmin::Devise.config

  devise_for :users, path_names: { sign_up: 'register' },
             controllers: {  omniauth_callbacks:  'users/omniauth_callbacks',
                             sessions:            'sessions',
                             registrations:       'registrations',
                             passwords:           'passwords'
             }

  get 'pages/index'
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'category' => 'products#category'

  get 'dashboard' => 'users#dashboard'
  get 'user_info' => 'users#info'
  post 'account_settings' => 'users#account_settings'
  get 'order_list' => 'users#order_list'
  get 'order_details/:id' => 'users#order_details', as: :order_details
  get 'manage_address' => 'users#manage_address'

  get 'cart' => 'carts#cart'
  get 'cart_items' => 'carts#cart_items'
  get 'checkout' => 'orders#checkout', :as => :checkout
  get 'shipping_info' => 'orders#shipping_info', as: :shipping_info
  get 'billing_info' => 'orders#billing_info', :as => :billing_info
  get 'shipping_method' => 'orders#shipping_method', :as => :shipping_method
  get 'payment_info' => 'orders#payment_info', :as => :payment_info
  get 'review_order' => 'orders#review_order', :as => :review_order
  get 'confirm_order' => 'orders#confirm_order'
  get 'remove_item_from_cart/:id' => 'line_items#remove_item_from_cart'
  post 'save_shipping_address' => 'orders#save_shipping_address', as: :save_shipping_address, via: [:post]
  get 'filter_products' => 'products#filter_products'

  root 'pages#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  ####<$ Model Association $>####
  has_many :line_items
  has_one :order

  ####<$ Validation $>####
  # validates_presence_of :shipping_cost
  #
  def add_product(product, quantity = 1)
    current_item = self.line_items.find_by_product_id(product.id)
    if current_item
      current_item.quantity += 1
      current_item.save
    else
      current_item = self.line_items.build(product_id: product.id, cart_id: self.id, quantity: quantity, product_price: product.price)
    end
    current_item
  end

  def cart_items
    line_items = self.line_items

    items = []
    line_items.each do |item|
      product = item.product
      item_j = {
          id: item.id,
          image: product.product_photos.first.image_url(:thumb_medium),
          name: product.name,
          price: product.price,
          quantity: item.quantity
      }

      items << item_j
    end

    items
  end

  def cart_total
    self.line_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def cart
    @cart_items = LineItem.where(:cart_id => session[:cart_id])
  end

  def cart_items
    cart = current_cart
    cart_items = cart.cart_items

    respond_to do |format|
      format.json { render json: cart_items, status: :ok }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_checkout_sidebar.html.haml
.contentBox
  .w100.costDetails
    #order-detail-content.table-block
      %a.btn.btn-primary.btn-lg.btn-block{:href => '/checkout', :style => "margin-bottom:20px", :title => "checkout"}
        Proceed to checkout &nbsp;
        %i.fa.fa-arrow-right
      .w100.cartMiniTable
        %table#cart-summary.std.table
          %tbody
            %tr
              %td Total products
              %td.price
                {{ grandTotal() }} tk
            %tr{:style => ""}
              %td Shipping
              %td.price
                %span.success Free shipping!
            %tr
              %td Total
              %td#total-price.site-color
                {{ grandTotal() }} tk
            -#%tr
            -#  %td{:colspan => "2"}
            -#    .input-append.couponForm
            -#      %input#appendedInputButton.col-lg-8{:placeholder => "Coupon code", :type => "text"}
            -#        %button.col-lg-4.btn.btn-success{:type => "button"} Apply!
          %tbody

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shipping_cost %><br>
    <%= f.text_field :shipping_cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/cart.html.haml
.container.main-container.headerOffset
  .row
    .breadcrumbDiv.col-lg-12
      %ul.breadcrumb
        %li
          %a{:href => '/'} Home
        %li.active Cart
  / /.row
  .row
    .col-lg-9.col-md-9.col-sm-7
      %h1.section-title-inner
        %span
          %i.glyphicon.glyphicon-shopping-cart
          Shopping cart
    .col-lg-3.col-md-3.col-sm-5.rightSidebar
      %h4.caps
        %a{:href => '/'}
          %i.fa.fa-chevron-left
          Back to shopping
  / /.row
  .row
    .col-lg-9.col-md-9.col-sm-7
      .row.userInfo
        .col-xs-12.col-sm-12
          .cartContent.w100
            %table.cartTable.table-responsive{:style => 'width:100%'}
              %thead
                %tr.CartProduct.cartTableHeader
                  %td{:style => 'width:15%'} Product
                  %td{:style => 'width:40%'} Details
                  %td.delete{:style => 'width:10%'} &nbsp;
                  %td{:style => 'width:10%'} QNT
                  %td{:style => 'width:10%'} Discount
                  %td{:style => 'width:15%'} Total
                -#
                -#- if @cart_items.present?
                -#  - @cart_items.each do |cart|
                -#    %tr.CartProduct
                -#      %td.CartProductThumb
                -#        %div
                -#          = link_to product_path(cart.product.id) do
                -#            = image_tag cart.product.product_photos.first.image_url(:thumb_medium)
                -#      %td
                -#        .CartDescription
                -#          %h4
                -#            = link_to cart.product.name, product_path(cart.product.id)
                -#          -#%span.size 12 x 1.5 L
                -#          .price
                -#            %span
                -#              = to_bdt(cart.product.price)
                -#      %td.delete
                -#        %a{:title => "Delete"}
                -#        %a{'ng-click' => 'removeItem(item.id)', :title => 'Delete'}
                -#          %i.glyphicon.glyphicon-trash.fa-2x
                -#
                -#      %td
                -#        %input.quanitySniper.form-control{:name => "quanitySniper", :type => "text", :value => cart.quantity}
                -#
                -#      %td 0
                -#      %td.price
                -#        = to_bdt(cart.product.price * cart.quantity)
                %tbody{ 'ng-repeat' => 'item in cartItems' }
                  %tr.CartProduct
                    %td.CartProductThumb
                      %div
                        %a{:href => '#'}
                          <img ng-src="{{ item.image }}">
                    %td
                      .CartDescription
                        %h4
                          %a{:href => '#'} {{ item.name }}
                        -#%span.size 12 x 1.5 L
                        .price
                          %span
                            {{ item.price }} tk
                    %td.delete
                      %a{'ng-click' => 'removeItem(item.id)', :title => 'Delete'}
                        %i.glyphicon.glyphicon-trash.fa-2x

                    %td
                      %input.quanitySniper.form-control{:name => 'quanitySniper', :type => 'text', :value => '{{item.quantity}}'}

                    %td 0
                    %td.price
                      {{ item.price * item.quantity }} tk
          / cartContent
          .cartFooter.w100
            .box-footer
              .pull-left
                %a.btn.btn-default{:href => '/'}
                  %i.fa.fa-arrow-left
                  \&nbsp; Continue shopping
              .pull-right
                %button.btn.btn-default{:type => 'submit'}
                  %i.fa.fa-undo
                  \&nbsp; Update cart

    .col-lg-3.col-md-3.col-sm-5.rightSidebar
      = render :partial => 'checkout_sidebar'

  %div{:style => 'clear:both'}
.gap

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>Shipping cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.shipping_cost %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shipping cost:</strong>
  <%= @cart.shipping_cost %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>